apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: PG
    type: postgres
    access: proxy
    url: pgvector:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
